import { JSX } from 'react';
import {
  FiHome,
  FiUser,
  FiSettings,
  FiMail,
  FiKey,
  FiBell,
  FiCalendar,
  FiClock,
  FiHeart,
  FiStar,
  FiBookmark,
  FiFlag,
  FiTrash2,
  FiEdit,
  FiCopy,
  FiSave,
  FiUpload,
  FiDownload,
  FiCamera,
  FiVideo,
  FiMusic,
  FiImage,
  FiFile,
  FiFolder,
  FiDatabase,
  FiCloud,
  FiServer,
  FiCpu,
  FiCode,
  FiTerminal,
  FiBox,
  FiGrid,
  FiLayers,
  FiLayout,
  FiMenu,
  FiX,
  FiCheck,
  FiAlertCircle,
  FiAlertTriangle,
  FiInfo,
  FiHelpCircle,
  FiSearch,
  FiZoomIn,
  FiZoomOut,
  FiMaximize,
  FiMinimize,
  FiPlus,
  FiMinus,
  FiArrowUp,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiChevronUp,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronsUp,
  FiChevronsDown,
  FiChevronsLeft,
  FiChevronsRight,
  FiExternalLink,
  FiLink,
  FiPaperclip,
  FiSend,
  FiMessageCircle,
  FiMessageSquare,
  FiPhone,
  FiPhoneCall,
  FiVideoOff,
  FiMic,
  FiMicOff,
  FiVolume2,
  FiVolumeX,
  FiHeadphones,
  FiRadio,
  FiActivity,
  FiBarChart2,
  FiPieChart,
  FiTrendingUp,
  FiTrendingDown,
  FiDollarSign,
  FiCreditCard,
  FiShoppingCart,
  FiGift,
  FiAward,
  FiZap,
  FiWind,
  FiSun,
  FiMoon,
  FiCloudRain,
  FiCloudSnow,
  FiCloudLightning,
  FiDroplet,
  FiThermometer,
  FiCompass,
  FiMap,
  FiMapPin,
  FiNavigation,
  FiAnchor,
  FiFeather,
  FiGlobe,
  FiTool,
  FiScissors,
  FiPenTool,
  FiEye,
  FiEyeOff,
  FiLock,
  FiUnlock,
  FiShield,
  FiShieldOff,
} from 'react-icons/fi';

export interface IconItem {
  id: string;
  name: string;
  icon: JSX.Element;
  category: string;
  tags: string[];
}

export const iconCategories = [
  { id: 'all', name: 'All Icons', color: '#94a3b8' },
  { id: 'ui', name: 'UI & Navigation', color: '#c5e6ff' },
  { id: 'media', name: 'Media & Files', color: '#ffb7c5' },
  { id: 'arrows', name: 'Arrows & Chevrons', color: '#d2b7ff' },
  { id: 'communication', name: 'Communication', color: '#b7ffca' },
  { id: 'weather', name: 'Weather & Nature', color: '#ffb7c5' },
  { id: 'tools', name: 'Tools & Actions', color: '#c5e6ff' },
];

export const getCategoryColor = (category: string) => {
  switch (category) {
    case 'ui': return '#c5e6ff';
    case 'media': return '#ffb7c5';
    case 'arrows': return '#d2b7ff';
    case 'communication': return '#b7ffca';
    case 'weather': return '#ffb7c5';
    case 'tools': return '#c5e6ff';
    default: return '#94a3b8';
  }
};

export const iconData: IconItem[] = [
  // UI & Navigation
  { id: '1', name: 'FiHome', icon: <FiHome size={24} />, category: 'ui', tags: ['home', 'house', 'dashboard'] },
  { id: '2', name: 'FiUser', icon: <FiUser size={24} />, category: 'ui', tags: ['user', 'profile', 'avatar'] },
  { id: '3', name: 'FiSettings', icon: <FiSettings size={24} />, category: 'ui', tags: ['settings', 'gear', 'preferences'] },
  { id: '4', name: 'FiMail', icon: <FiMail size={24} />, category: 'communication', tags: ['mail', 'email', 'message'] },
  { id: '5', name: 'FiLock', icon: <FiLock size={24} />, category: 'ui', tags: ['lock', 'security', 'private'] },
  { id: '6', name: 'FiKey', icon: <FiKey size={24} />, category: 'ui', tags: ['key', 'password', 'access'] },
  { id: '7', name: 'FiBell', icon: <FiBell size={24} />, category: 'ui', tags: ['bell', 'notification', 'alert'] },
  { id: '8', name: 'FiCalendar', icon: <FiCalendar size={24} />, category: 'ui', tags: ['calendar', 'date', 'event'] },
  { id: '9', name: 'FiClock', icon: <FiClock size={24} />, category: 'ui', tags: ['clock', 'time', 'schedule'] },
  { id: '10', name: 'FiHeart', icon: <FiHeart size={24} />, category: 'ui', tags: ['heart', 'like', 'favorite'] },
  { id: '11', name: 'FiStar', icon: <FiStar size={24} />, category: 'ui', tags: ['star', 'rating', 'favorite'] },
  { id: '12', name: 'FiBookmark', icon: <FiBookmark size={24} />, category: 'ui', tags: ['bookmark', 'save', 'tag'] },
  { id: '13', name: 'FiFlag', icon: <FiFlag size={24} />, category: 'ui', tags: ['flag', 'report', 'milestone'] },
  { id: '14', name: 'FiTrash2', icon: <FiTrash2 size={24} />, category: 'tools', tags: ['trash', 'delete', 'remove'] },
  { id: '15', name: 'FiEdit', icon: <FiEdit size={24} />, category: 'tools', tags: ['edit', 'pencil', 'write'] },
  { id: '16', name: 'FiCopy', icon: <FiCopy size={24} />, category: 'tools', tags: ['copy', 'duplicate', 'clone'] },
  { id: '17', name: 'FiSave', icon: <FiSave size={24} />, category: 'tools', tags: ['save', 'disk', 'store'] },
  { id: '18', name: 'FiUpload', icon: <FiUpload size={24} />, category: 'media', tags: ['upload', 'export', 'share'] },
  { id: '19', name: 'FiDownload', icon: <FiDownload size={24} />, category: 'media', tags: ['download', 'import', 'save'] },
  { id: '20', name: 'FiCamera', icon: <FiCamera size={24} />, category: 'media', tags: ['camera', 'photo', 'image'] },
  { id: '21', name: 'FiVideo', icon: <FiVideo size={24} />, category: 'media', tags: ['video', 'camera', 'record'] },
  { id: '22', name: 'FiMusic', icon: <FiMusic size={24} />, category: 'media', tags: ['music', 'audio', 'sound'] },
  { id: '23', name: 'FiImage', icon: <FiImage size={24} />, category: 'media', tags: ['image', 'picture', 'photo'] },
  { id: '24', name: 'FiFile', icon: <FiFile size={24} />, category: 'media', tags: ['file', 'document', 'paper'] },
  { id: '25', name: 'FiFolder', icon: <FiFolder size={24} />, category: 'media', tags: ['folder', 'directory', 'storage'] },
  { id: '26', name: 'FiDatabase', icon: <FiDatabase size={24} />, category: 'media', tags: ['database', 'data', 'storage'] },
  { id: '27', name: 'FiCloud', icon: <FiCloud size={24} />, category: 'weather', tags: ['cloud', 'storage', 'online'] },
  { id: '28', name: 'FiServer', icon: <FiServer size={24} />, category: 'media', tags: ['server', 'hosting', 'backend'] },
  { id: '29', name: 'FiCpu', icon: <FiCpu size={24} />, category: 'media', tags: ['cpu', 'processor', 'hardware'] },
  { id: '30', name: 'FiCode', icon: <FiCode size={24} />, category: 'media', tags: ['code', 'developer', 'programming'] },
  { id: '31', name: 'FiTerminal', icon: <FiTerminal size={24} />, category: 'media', tags: ['terminal', 'command', 'cli'] },
  { id: '32', name: 'FiBox', icon: <FiBox size={24} />, category: 'ui', tags: ['box', 'cube', 'package'] },
  { id: '33', name: 'FiGrid', icon: <FiGrid size={24} />, category: 'ui', tags: ['grid', 'layout', 'dashboard'] },
  { id: '34', name: 'FiLayers', icon: <FiLayers size={24} />, category: 'ui', tags: ['layers', 'stack', 'design'] },
  { id: '35', name: 'FiLayout', icon: <FiLayout size={24} />, category: 'ui', tags: ['layout', 'design', 'template'] },
  { id: '36', name: 'FiMenu', icon: <FiMenu size={24} />, category: 'ui', tags: ['menu', 'hamburger', 'navigation'] },
  { id: '37', name: 'FiX', icon: <FiX size={24} />, category: 'ui', tags: ['close', 'x', 'cancel'] },
  { id: '38', name: 'FiCheck', icon: <FiCheck size={24} />, category: 'ui', tags: ['check', 'tick', 'done'] },
  { id: '39', name: 'FiAlertCircle', icon: <FiAlertCircle size={24} />, category: 'ui', tags: ['alert', 'error', 'warning'] },
  { id: '40', name: 'FiAlertTriangle', icon: <FiAlertTriangle size={24} />, category: 'ui', tags: ['warning', 'danger', 'caution'] },
  { id: '41', name: 'FiInfo', icon: <FiInfo size={24} />, category: 'ui', tags: ['info', 'information', 'help'] },
  { id: '42', name: 'FiHelpCircle', icon: <FiHelpCircle size={24} />, category: 'ui', tags: ['help', 'question', 'support'] },
  { id: '43', name: 'FiSearch', icon: <FiSearch size={24} />, category: 'ui', tags: ['search', 'find', 'magnify'] },

  // Arrows & Chevrons
  { id: '44', name: 'FiArrowUp', icon: <FiArrowUp size={24} />, category: 'arrows', tags: ['arrow', 'up', 'top'] },
  { id: '45', name: 'FiArrowDown', icon: <FiArrowDown size={24} />, category: 'arrows', tags: ['arrow', 'down', 'bottom'] },
  { id: '46', name: 'FiArrowLeft', icon: <FiArrowLeft size={24} />, category: 'arrows', tags: ['arrow', 'left', 'back'] },
  { id: '47', name: 'FiArrowRight', icon: <FiArrowRight size={24} />, category: 'arrows', tags: ['arrow', 'right', 'next'] },
  { id: '48', name: 'FiChevronUp', icon: <FiChevronUp size={24} />, category: 'arrows', tags: ['chevron', 'up', 'collapse'] },
  { id: '49', name: 'FiChevronDown', icon: <FiChevronDown size={24} />, category: 'arrows', tags: ['chevron', 'down', 'expand'] },
  { id: '50', name: 'FiChevronLeft', icon: <FiChevronLeft size={24} />, category: 'arrows', tags: ['chevron', 'left', 'previous'] },
  { id: '51', name: 'FiChevronRight', icon: <FiChevronRight size={24} />, category: 'arrows', tags: ['chevron', 'right', 'next'] },
  { id: '52', name: 'FiChevronsUp', icon: <FiChevronsUp size={24} />, category: 'arrows', tags: ['chevrons', 'up', 'top'] },
  { id: '53', name: 'FiChevronsDown', icon: <FiChevronsDown size={24} />, category: 'arrows', tags: ['chevrons', 'down', 'bottom'] },
  { id: '54', name: 'FiChevronsLeft', icon: <FiChevronsLeft size={24} />, category: 'arrows', tags: ['chevrons', 'left', 'first'] },
  { id: '55', name: 'FiChevronsRight', icon: <FiChevronsRight size={24} />, category: 'arrows', tags: ['chevrons', 'right', 'last'] },
  { id: '56', name: 'FiExternalLink', icon: <FiExternalLink size={24} />, category: 'arrows', tags: ['external', 'link', 'open'] },
  { id: '57', name: 'FiLink', icon: <FiLink size={24} />, category: 'arrows', tags: ['link', 'chain', 'url'] },

  // Communication
  { id: '58', name: 'FiSend', icon: <FiSend size={24} />, category: 'communication', tags: ['send', 'message', 'paper-plane'] },
  { id: '59', name: 'FiMessageCircle', icon: <FiMessageCircle size={24} />, category: 'communication', tags: ['message', 'chat', 'bubble'] },
  { id: '60', name: 'FiMessageSquare', icon: <FiMessageSquare size={24} />, category: 'communication', tags: ['message', 'chat', 'square'] },
  { id: '61', name: 'FiPhone', icon: <FiPhone size={24} />, category: 'communication', tags: ['phone', 'call', 'contact'] },
  { id: '62', name: 'FiPhoneCall', icon: <FiPhoneCall size={24} />, category: 'communication', tags: ['phone', 'call', 'ring'] },
  { id: '63', name: 'FiMic', icon: <FiMic size={24} />, category: 'communication', tags: ['mic', 'microphone', 'voice'] },
  { id: '64', name: 'FiMicOff', icon: <FiMicOff size={24} />, category: 'communication', tags: ['mic', 'mute', 'off'] },
  { id: '65', name: 'FiVideoOff', icon: <FiVideoOff size={24} />, category: 'communication', tags: ['video', 'camera', 'off'] },

  // Weather & Nature
  { id: '66', name: 'FiSun', icon: <FiSun size={24} />, category: 'weather', tags: ['sun', 'light', 'day'] },
  { id: '67', name: 'FiMoon', icon: <FiMoon size={24} />, category: 'weather', tags: ['moon', 'night', 'dark'] },
  { id: '68', name: 'FiCloudRain', icon: <FiCloudRain size={24} />, category: 'weather', tags: ['rain', 'cloud', 'weather'] },
  { id: '69', name: 'FiCloudSnow', icon: <FiCloudSnow size={24} />, category: 'weather', tags: ['snow', 'winter', 'cold'] },
  { id: '70', name: 'FiCloudLightning', icon: <FiCloudLightning size={24} />, category: 'weather', tags: ['lightning', 'storm', 'thunder'] },
  { id: '71', name: 'FiDroplet', icon: <FiDroplet size={24} />, category: 'weather', tags: ['droplet', 'water', 'rain'] },
  { id: '72', name: 'FiWind', icon: <FiWind size={24} />, category: 'weather', tags: ['wind', 'air', 'breeze'] },
  { id: '73', name: 'FiCompass', icon: <FiCompass size={24} />, category: 'weather', tags: ['compass', 'direction', 'navigation'] },
  { id: '74', name: 'FiMap', icon: <FiMap size={24} />, category: 'weather', tags: ['map', 'location', 'travel'] },
  { id: '75', name: 'FiMapPin', icon: <FiMapPin size={24} />, category: 'weather', tags: ['pin', 'location', 'marker'] },
  { id: '76', name: 'FiFeather', icon: <FiFeather size={24} />, category: 'weather', tags: ['feather', 'light', 'write'] },
  { id: '77', name: 'FiGlobe', icon: <FiGlobe size={24} />, category: 'weather', tags: ['globe', 'world', 'earth'] },

  // Tools & Actions
  { id: '78', name: 'FiTool', icon: <FiTool size={24} />, category: 'tools', tags: ['tool', 'fix', 'repair'] },
  { id: '81', name: 'FiScissors', icon: <FiScissors size={24} />, category: 'tools', tags: ['scissors', 'cut', 'trim'] },
  { id: '82', name: 'FiPenTool', icon: <FiPenTool size={24} />, category: 'tools', tags: ['pen', 'draw', 'design'] },
  { id: '86', name: 'FiEye', icon: <FiEye size={24} />, category: 'tools', tags: ['eye', 'view', 'show'] },
  { id: '87', name: 'FiEyeOff', icon: <FiEyeOff size={24} />, category: 'tools', tags: ['eye', 'hide', 'invisible'] },
  { id: '88', name: 'FiUnlock', icon: <FiUnlock size={24} />, category: 'tools', tags: ['unlock', 'open', 'security'] },
  { id: '89', name: 'FiShield', icon: <FiShield size={24} />, category: 'tools', tags: ['shield', 'security', 'protection'] },
  { id: '90', name: 'FiZap', icon: <FiZap size={24} />, category: 'tools', tags: ['zap', 'lightning', 'energy'] },
  { id: '91', name: 'FiAward', icon: <FiAward size={24} />, category: 'tools', tags: ['award', 'achievement', 'badge'] },
  { id: '92', name: 'FiActivity', icon: <FiActivity size={24} />, category: 'tools', tags: ['activity', 'graph', 'trend'] },
  { id: '93', name: 'FiBarChart2', icon: <FiBarChart2 size={24} />, category: 'tools', tags: ['chart', 'graph', 'stats'] },
  { id: '94', name: 'FiTrendingUp', icon: <FiTrendingUp size={24} />, category: 'tools', tags: ['trend', 'up', 'growth'] },
  { id: '95', name: 'FiDollarSign', icon: <FiDollarSign size={24} />, category: 'tools', tags: ['dollar', 'money', 'payment'] },
  { id: '96', name: 'FiCreditCard', icon: <FiCreditCard size={24} />, category: 'tools', tags: ['credit', 'card', 'payment'] },
  { id: '97', name: 'FiShoppingCart', icon: <FiShoppingCart size={24} />, category: 'tools', tags: ['cart', 'shop', 'store'] },
  { id: '98', name: 'FiGift', icon: <FiGift size={24} />, category: 'tools', tags: ['gift', 'present', 'birthday'] },
];
